CircleCI: Authenticate requests & dump GitHub ratelimit headers on failure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -93,7 +93,10 @@ jobs:
             fetched=false
             for i in $(seq 1 5); do
               echo ""
-              res=$(curl -fsS https://api.github.com/repos/arangodb/docs-hugo/contents/.circleci?ref=$CIRCLE_SHA1) || curlStatus=$?
+              headers=$(mktemp)
+              res=$(curl -sS -D "$headers" -H "Authorization: Bearer $CIRCLECI_GITHUB_READONLY" https://api.github.com/repos/arangodb/docs-hugo/contents/.circleci?ref=$CIRCLE_SHA1) || curlStatus=$?
+              headers_content=$(cat "$headers")
+              rm "$headers"
               if [[ -z "${curlStatus:-}" ]]; then
                 urls=$(echo "$res" | jq ".[].download_url") || jqStatus=$?
                 if [[ -z "${jqStatus:-}" ]]; then
@@ -103,7 +106,8 @@ jobs:
                 echo "jq failed with $jqStatus, input:"
                 echo "$res"
               else
-                echo "curl failed with $curlStatus"
+                echo "curl failed with $curlStatus, rate limit?"
+                echo "$headers_content" | grep -i "ratelimit\|retry-after"
               fi
               unset curlStatus
               unset jqStatus
@@ -113,8 +117,8 @@ jobs:
               echo "Failed to fetch download URLs"
               exit 1
             fi
-            echo "$urls" | xargs wget
-            wget https://raw.githubusercontent.com/arangodb/docs-hugo/$CIRCLE_SHA1/site/data/versions.yaml
+            echo "$urls" | xargs -n 1 curl -sS -O -H "Authorization: Bearer $CIRCLECI_GITHUB_READONLY"
+            curl -sS -O -H "Authorization: Bearer $CIRCLECI_GITHUB_READONLY" https://raw.githubusercontent.com/arangodb/docs-hugo/$CIRCLE_SHA1/site/data/versions.yaml
 
             pip install pyyaml requests
 
